name: Lint C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get cppcheck
      run: sudo apt-get install -y cppcheck
    - name: Lint using cppcheck
      run: cppcheck .
