name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Eclipse
      run: sudo snap install --classic eclipse
    - name: check eclipse
      run: eclipse -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -import . -cleanBuild PSES/Debug
