name: Eclipse CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Eclipse
      run: cd .. && wget "http://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/technology/epp/downloads/release/2022-09/R/eclipse-cpp-2022-09-R-linux-gtk-x86_64.tar.gz" && sudo tar xf eclipse-cpp-2022-09-R-linux-gtk-x86_64.tar.gz -C /opt && sudo ln -s /opt/eclipse/eclipse /usr/local/bin/
    - name: Build using Eclipse
      run: cd .. && eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data . -importAll . -build PSES/Debug -no-indexer
    - name: Run Debug build
      run: cd Debug && ./PSES
